import { Inter } from "next/font/google";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import { Header } from "@/components/Header/Header";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} bg-background text-foreground`}>
          {/* header */}
          <Header />
         <main className="min-h-screen pt-12">{children}</main>

          <footer className="bg-gray-400 border-t border-accent/20 py-12 text-center text-sm text-accent">
            Copyright 2025 - All rights reserved
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
